### ISSUE TITLE
Need to Add CSS Animations on Dice image 

### ISSUE THREAD

**Issue by rifat328** [rifat328/Dice-Game-Challenge#1]
### ** Add CSS Animations on the Dice image for both players**
![image](https://github.com/user-attachments/assets/acd69ab3-2aab-49a5-a718-037b60d1954a)

**Comment by qbinh1423** [comment]
Hello! I am a newbie coder. Can I try this issue? I really appreciate this opportunity. Thank you!

**Comment by rifat328** [comment]
Yeah Sure, I am Also new to JavaScript, and going through exercises as well. and thank you for Contributing.

> Hello! I am a newbie coder. Can I try this issue? I really appreciate this opportunity. Thank you!

**Comment by qbinh1423** [comment]
I have created a fork link from your project and uploaded mine. I have made a few adjustments in CSS file to add a 3D effect, create dice using 'transform' and 'box-shadow' to create pips. You can check out that project and give me a review. Thanks!

**Comment by rifat328** [comment]
there is a problem after the deployment  on github it dosent' work , or when only clicking index.js , similar issue but .
when lunching with vs code live server it works fine ,

**Comment by rifat328** [comment]
there is a problem after the deployment on github it dosent' work , or when only clicking index.jhtml , similar issue but .
when launching with vs code live server it works fine.
